
services:

  server:
    image: "ubuntu:latest"
    container_name: server
    tty: true
    entrypoint: /bin/bash /comfystack/server/init-ubuntu.sh
    ports:
      - "5000:${SERVER_PORT}"
    networks:
      - comfynetwork
    volumes:
      - "./../server/:/comfystack/server/:rw" # Deve essere rw dato il download delle dependencies. In alternativa, è da deferire a un init script

  postgres:
    image: "postgres:alpine"
    container_name: postgres
    ports:
      - 5200:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - comfynetwork
    restart: always 
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

volumes:
  postgres-data:
  comfystack:
networks:
  comfynetwork: